version: 0.2

env:
  variables:
    CI: 'true'

phases:
  install:
    commands:
      - pip3 install awscli --upgrade --user
      - npm ci

  build:
    commands:
      - export package=$(npm pack)
      - mkdir dist
      - tar -C dist -xvf ${package}
      - cd dist/package
      - npm i --production
      - rm package-lock.json
      - cd ../../
      - npm run swagger:bundle
      - export DEFINITION_KEY=s3://$ARTIFACT_BUCKET/definitions/$CODEBUILD_RESOLVED_SOURCE_VERSION.json
      - aws s3 cp swagger/bundle.spec.json $DEFINITION_KEY --sse aws:kms --sse-kms-key-id $ENCRYPTION_KEY
      - node -e 'console.log(JSON.stringify(process.env))' > build.json

  post_build:
    commands:
      - >
        aws cloudformation package -- \
          --template-file .ci/service.yml \
          --output-template-file packaged.yml \
          --kms-key-id $ENCRYPTION_KEY \
          --s3-bucket $ARTIFACT_BUCKET \
          --s3-prefix consumers/

artifacts:
  type: zip
  discard-paths: yes
  files:
    - 'build.json'
    - 'packaged.yml'
