#!/bin/bash

[[ ! $1 ]] && { echo "Missing profile" >&1; exit 1; }
[[ ! $2 ]] && { echo "Missing region" >&2; exit 1; }

aws cloudformation create-stack --template-body file://pipeline.yml --cli-input-json file://parameters.json --profile "$1" --region "$2"

exit 0
