swagger: '2.0'

info:
  description: |
    Plinc API
  version: 1.0.0
  title: plinc-api

paths:
  /hello:
    get:
      summary: Say Hello
      responses:
        200:
          description: OK
      x-amazon-apigateway-integration:
        type: aws
        httpMethod: 'GET'
        uri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path//2015-03-31/functions/${HelloFunction.Arn}/invocations'
        responses:
          default:
            statusCode: '200'
          4\d{2}:
            statusCode: '400'
          5\d{2}:
            statusCode: '500'

definitions:
  Message:
    type: object
    properties:
      message: string
