version: 0.2

env:
  variables:
    CI: 'true'
    SKIP_PREFLIGHT_CHECK: 'true'

phases:
  install:
    commands:
      - npm ci

  pre_build:
    commands:
    - npm run swagger:convert

  build:
    commands:
      - npm run swagger:build

artifacts:
  files:
    - '**/*'
  discard-paths: false
  base-directory: .swagger-dist/
