Authorizer:
  type: apiKey
  name: Authorization
  in: header
  x-amazon-apigateway-authtype: cognito_user_pools
  x-amazon-apigateway-authorizer:
    providerARNs:
    - Fn::Sub: "arn:${AWS::Partition}:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}"
    type: cognito_user_pools
